// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tmf683.PartyInteraction.Api.Data;

#nullable disable

namespace Tmf683.PartyInteraction.Api.Migrations
{
    [DbContext(typeof(PartyInteractionDbContext))]
    [Migration("20250904142522_AddAuditFieldsToPartyInteraction")]
    partial class AddAuditFieldsToPartyInteraction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tmf683.PartyInteraction.Api.Models.PartyInteract", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InteractionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PartyInteractions");
                });

            modelBuilder.Entity("Tmf683.PartyInteraction.Api.Models.RelatedPartyRef", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PartyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartyInteractId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PartyInteractionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PartyInteractId");

                    b.ToTable("RelatedPartyRefs");
                });

            modelBuilder.Entity("Tmf683.PartyInteraction.Api.Models.RelatedPartyRef", b =>
                {
                    b.HasOne("Tmf683.PartyInteraction.Api.Models.PartyInteract", null)
                        .WithMany("RelatedParty")
                        .HasForeignKey("PartyInteractId");
                });

            modelBuilder.Entity("Tmf683.PartyInteraction.Api.Models.PartyInteract", b =>
                {
                    b.Navigation("RelatedParty");
                });
#pragma warning restore 612, 618
        }
    }
}
