// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tmf632.PartyManagement.Api.Data;

#nullable disable

namespace Tmf632.PartyManagement.Api.Migrations
{
    [DbContext(typeof(PartyManagementDbContext))]
    [Migration("20250829153615_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tmf632.PartyManagement.Api.Models.Characteristic", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IndividualId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IndividualId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Characteristic");
                });

            modelBuilder.Entity("Tmf632.PartyManagement.Api.Models.ContactMedium", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IndividualId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MediumType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Preferred")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IndividualId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("ContactMedium");
                });

            modelBuilder.Entity("Tmf632.PartyManagement.Api.Models.Individual", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Individuals");
                });

            modelBuilder.Entity("Tmf632.PartyManagement.Api.Models.Organization", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IsHeadOffice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TradingName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("Tmf632.PartyManagement.Api.Models.RelatedParty", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IndividualId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OrganizationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PartyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IndividualId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("RelatedParty");
                });

            modelBuilder.Entity("Tmf632.PartyManagement.Api.Models.Characteristic", b =>
                {
                    b.HasOne("Tmf632.PartyManagement.Api.Models.Individual", null)
                        .WithMany("Characteristic")
                        .HasForeignKey("IndividualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tmf632.PartyManagement.Api.Models.Organization", null)
                        .WithMany("Characteristic")
                        .HasForeignKey("OrganizationId");
                });

            modelBuilder.Entity("Tmf632.PartyManagement.Api.Models.ContactMedium", b =>
                {
                    b.HasOne("Tmf632.PartyManagement.Api.Models.Individual", null)
                        .WithMany("ContactMedium")
                        .HasForeignKey("IndividualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tmf632.PartyManagement.Api.Models.Organization", null)
                        .WithMany("ContactMedium")
                        .HasForeignKey("OrganizationId");
                });

            modelBuilder.Entity("Tmf632.PartyManagement.Api.Models.RelatedParty", b =>
                {
                    b.HasOne("Tmf632.PartyManagement.Api.Models.Individual", null)
                        .WithMany("RelatedParty")
                        .HasForeignKey("IndividualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tmf632.PartyManagement.Api.Models.Organization", null)
                        .WithMany("RelatedParty")
                        .HasForeignKey("OrganizationId");
                });

            modelBuilder.Entity("Tmf632.PartyManagement.Api.Models.Individual", b =>
                {
                    b.Navigation("Characteristic");

                    b.Navigation("ContactMedium");

                    b.Navigation("RelatedParty");
                });

            modelBuilder.Entity("Tmf632.PartyManagement.Api.Models.Organization", b =>
                {
                    b.Navigation("Characteristic");

                    b.Navigation("ContactMedium");

                    b.Navigation("RelatedParty");
                });
#pragma warning restore 612, 618
        }
    }
}
